version: '3.9'

services: 
    go_api:
        image: ffelixneto/router:1.0.0
        ports:
            - 8080:8080
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
            resources:
                reservations:
                    cpus: '0.20'
                    memory: 50M
                limits:
                    cpus: '0.30'
                    memory: 100M